// Durable conversation log for the AI Concierge (Vercel Postgres / Neon).
//
// Two non-negotiables shaped this file:
//
// 1. THE CHAT MUST NEVER BREAK BECAUSE OF LOGGING. The database is optional.
//    If POSTGRES_URL is unset (it is, until the store is provisioned), if the
//    driver isn't installed, or if a write fails, every function here degrades
//    to a no-op and the customer still gets their answer. Logging is a
//    business convenience; answering is the product.
//
// 2. NOTHING UNREDACTED IS WRITTEN. Callers pass text through api/_redact.js
//    first. This module does not see raw customer input by design, so a
//    mistake here cannot leak a PIN.
//
// Writes are fire-and-forget, issued after the response has already been
// streamed to the customer, so logging never adds latency to a reply.

let sqlPromise = null;
let schemaReady = false;

/** Lazily resolves the driver. Returns null when logging is not configured. */
async function getSql() {
  if (!process.env.POSTGRES_URL) return null;
  if (!sqlPromise) {
    sqlPromise = import("@vercel/postgres")
      .then((m) => m.sql)
      .catch((e) => {
        console.error(JSON.stringify({ event: "store_driver_missing", error: String(e.message || e).slice(0, 120) }));
        return null;
      });
  }
  return sqlPromise;
}

export function storeEnabled() {
  return !!process.env.POSTGRES_URL;
}

// Created on first write rather than in a migration step, because this app has
// no migration runner and the schema is small enough that IF NOT EXISTS is
// honest. `unmatched` is the column that earns its keep: tokens a customer
// typed that scored against nothing in the catalog are exactly the synonyms
// the retriever is missing, and the raw material for tuning it.
async function ensureSchema(sql) {
  if (schemaReady) return;
  await sql`
    CREATE TABLE IF NOT EXISTS chat_turns (
      id          TEXT PRIMARY KEY,
      session_id  TEXT NOT NULL,
      turn        INT  NOT NULL,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
      question    TEXT,
      reply       TEXT,
      intent      JSONB,
      retrieved   TEXT[],
      cards       TEXT[],
      unmatched   TEXT[],
      model       TEXT,
      latency_ms  INT,
      punted      BOOLEAN DEFAULT false,
      redactions  INT DEFAULT 0,
      feedback    SMALLINT
    )`;
  await sql`CREATE INDEX IF NOT EXISTS chat_turns_created_idx ON chat_turns (created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS chat_turns_session_idx ON chat_turns (session_id)`;
  schemaReady = true;
}

/**
 * Records one question/answer exchange. Never throws.
 *
 * The row id is generated by the caller before the write, not returned by it.
 * The widget needs an id to attach a thumbs-up to, and awaiting an INSERT to
 * learn that id would put a database round-trip in front of the customer's
 * reply — the one thing this module promised not to do.
 */
export async function logTurn(rec) {
  try {
    const sql = await getSql();
    if (!sql) return null;
    await ensureSchema(sql);
    await sql`
      INSERT INTO chat_turns
        (id, session_id, turn, question, reply, intent, retrieved, cards, unmatched, model, latency_ms, punted, redactions)
      VALUES
        (${rec.id}, ${rec.sessionId}, ${rec.turn}, ${rec.question}, ${rec.reply}, ${JSON.stringify(rec.intent ?? {})},
         ${rec.retrieved ?? []}, ${rec.cards ?? []}, ${rec.unmatched ?? []}, ${rec.model},
         ${rec.latencyMs}, ${rec.punted ?? false}, ${rec.redactions ?? 0})
      ON CONFLICT (id) DO NOTHING`;
    return rec.id;
  } catch (e) {
    console.error(JSON.stringify({ event: "store_write_failed", error: String(e.message || e).slice(0, 150) }));
    return null;
  }
}

/** Attaches a thumbs up/down to a previously logged turn. Never throws. */
export async function saveFeedback(turnId, value) {
  try {
    const sql = await getSql();
    if (!sql) return false;
    await ensureSchema(sql);
    await sql`UPDATE chat_turns SET feedback = ${value} WHERE id = ${turnId}`;
    return true;
  } catch (e) {
    console.error(JSON.stringify({ event: "store_feedback_failed", error: String(e.message || e).slice(0, 150) }));
    return false;
  }
}

/**
 * The improvement loop. Each query below answers a specific "where is the
 * assistant failing?" question, so the output is a work list rather than a
 * dashboard to admire.
 */
export async function buildInsights(days = 14) {
  const sql = await getSql();
  if (!sql) return null;
  await ensureSchema(sql);
  const since = `${days} days`;

  const [volume, gaps, unmatched, punts, negative, topProducts] = await Promise.all([
    sql`SELECT count(*)::int AS turns, count(DISTINCT session_id)::int AS sessions,
               round(avg(latency_ms))::int AS avg_latency_ms,
               sum(redactions)::int AS redactions
        FROM chat_turns WHERE created_at > now() - ${since}::interval`,

    // Answered, but matched no product at all — either a catalog gap or a
    // retrieval gap. The highest-value list in here.
    sql`SELECT question, count(*)::int AS n
        FROM chat_turns
        WHERE created_at > now() - ${since}::interval
          AND cardinality(cards) = 0 AND NOT punted
        GROUP BY question ORDER BY n DESC LIMIT 25`,

    // Words customers type that the catalog has no concept for. These become
    // TERMS entries in api/concierge.js.
    sql`SELECT term, count(*)::int AS n
        FROM chat_turns, unnest(unmatched) AS term
        WHERE created_at > now() - ${since}::interval
        GROUP BY term HAVING count(*) > 1 ORDER BY n DESC LIMIT 40`,

    sql`SELECT question, count(*)::int AS n
        FROM chat_turns
        WHERE created_at > now() - ${since}::interval AND punted
        GROUP BY question ORDER BY n DESC LIMIT 25`,

    sql`SELECT question, reply, created_at
        FROM chat_turns
        WHERE created_at > now() - ${since}::interval AND feedback = -1
        ORDER BY created_at DESC LIMIT 25`,

    sql`SELECT p AS product, count(*)::int AS n
        FROM chat_turns, unnest(cards) AS p
        WHERE created_at > now() - ${since}::interval
        GROUP BY p ORDER BY n DESC LIMIT 20`,
  ]);

  const v = volume.rows[0] ?? {};
  return {
    windowDays: days,
    volume: v,
    // Share of answers that produced nothing actionable — the single number
    // worth watching week to week.
    deadEndRate: v.turns ? Number((gaps.rows.reduce((a, r) => a + r.n, 0) / v.turns).toFixed(3)) : null,
    noProductMatched: gaps.rows,
    missingSynonyms: unmatched.rows,
    punted: punts.rows,
    thumbsDown: negative.rows,
    topRecommended: topProducts.rows,
  };
}
